spring.application.name=logistics-service

spring.mvc.format.date=yyyy-MM-dd

server.port=8083
management.endpoints.web.base-path=/actuator

order-service.url=http://localhost:8082

novaposhta.api.url=https://api.novaposhta.ua/v2.0/json/

novaposhta.api-key=afde099bebf4b21170c56a4624741da0
novaposhta.city-sender=f70622d2-4078-11de-b509-001d92f78698
novaposhta.sender=12a561c8-3564-11f0-a1d5-48df37b921da
novaposhta.sender-address=5a39e55c-e1c2-11e3-8c4a-0050568002cf
novaposhta.contact-sender=12a64d5b-3564-11f0-a1d5-48df37b921da
novaposhta.sender-phone=380964890788


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/artmarket
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/artmarket/protocol/openid-connect/certs

jwt.auth.converter.resource-id=user-service


spring.kafka.bootstrap-servers=localhost:29092

# Producer configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Consumer configuration
spring.kafka.consumer.group-id=logistics-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# Topic names
kafka.topics.order-created=order.created
kafka.topics.delivery-status-updated=delivery.status.updated
kafka.topics.delivery-errors=delivery.errors

spring.kafka.listener.ack-mode=RECORD
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.listener.retry.initial-interval=1000
spring.kafka.listener.retry.max-attempts=3
spring.kafka.listener.retry.max-interval=10000

logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=WARN
logging.level.com.example.logistics=DEBUG