spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5435/order_db
spring.datasource.username=postgres
spring.datasource.password=boomlog123321

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.main.allow-bean-definition-overriding=true

spring.mvc.format.date=yyyy-MM-dd

server.port=8082
management.endpoints.web.base-path=/actuator

painting-service.url=http://localhost:8080
user-service.url=http://localhost:8081


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/artmarket
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/artmarket/protocol/openid-connect/certs

jwt.auth.converter.resource-id=user-service

spring.kafka.bootstrap-servers=localhost:29092

# Producer configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Consumer configuration
spring.kafka.consumer.group-id=order-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=*

# Topic names
kafka.topics.order-created=order.created
kafka.topics.order-status-changed=order.status.changed
kafka.topics.order-updated=order.updated
kafka.topics.shipping-updated=shipping.updated